name: code validation

on:
  push:
    branches-ignore:
      - 'main'
      - 'v*.*.*'
      - '*.*.*'
jobs:
  validate:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    name: Validate Terraform Code
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: terraform validate
        uses: dflook/terraform-validate@v1

  format:
    needs: validate
    runs-on: ubuntu-latest
    name: Check Terraform Formatting
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: terraform fmt
        uses: dflook/terraform-fmt@v1

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: terraform fmt
          title: Reformat terraform files
          body: Update terraform files to canonical format using `terraform fmt`
          branch: automated-terraform-fmt  
  tflint:
    needs: format
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout source code

    - uses: terraform-linters/setup-tflint@v1
      name: Setup TFLint
      with:
        tflint_version: latest

    - name: Show version
      run: tflint --version

    - name: Init TFLint
      run: tflint --init

    - name: Run TFLint
      run: tflint -c tflint.hcl --force
      
  checkov-job:
    needs: tflint
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          framework: terraform
          skip_check: CKV2_AWS_12
          soft_fail: true